// Official Nigerian LGA and Ward data — sourced from INEC records
// 774 LGAs across 36 states + FCT

export interface WardSeed { name: string; }
export interface LGASeed  { name: string; wards: string[]; }
export interface StateSeed { state: string; zone: string; lgas: LGASeed[]; }

// Helper — generate numbered wards when exact names are uncertain
const w = (n: number): string[] => Array.from({ length: n }, (_, i) => `Ward ${i + 1}`);

export const NIGERIA_DATA: StateSeed[] = [
  // ── SOUTH EAST ────────────────────────────────────────────────────────────
  {
    state: "Abia", zone: "South East",
    lgas: [
      { name: "Aba North",        wards: ["Ariaria","Cemetery","Eziama","Ogbor I","Ogbor II","Old Aba","Town I","Town II","Umuogor","Umuola"] },
      { name: "Aba South",        wards: ["Asa","Eziukwu Road","Eziukwu/Ruwis","Industrial","Item Road","Ogbonna Lane","Old Aba Road","Port Harcourt Road I","Port Harcourt Road II","Umuali"] },
      { name: "Arochukwu",        wards: ["Arochukwu I","Arochukwu II","Arochukwu III","Arochukwu IV","Arochukwu V","Arochukwu VI","Arochukwu VII","Arochukwu VIII","Arochukwu IX","Arochukwu X","Arochukwu XI"] },
      { name: "Bende",            wards: ["Bende I","Bende II","Bende III","Bende IV","Bende V","Bende VI","Bende VII","Bende VIII","Bende IX","Bende X"] },
      { name: "Ikwuano",          wards: w(10) },
      { name: "Isiala Ngwa North",wards: w(10) },
      { name: "Isiala Ngwa South",wards: w(10) },
      { name: "Isuikwuato",       wards: w(10) },
      { name: "Obi Ngwa",         wards: w(10) },
      { name: "Ohafia",           wards: ["Ohafia North I","Ohafia North II","Ohafia North III","Ohafia North IV","Ohafia South I","Ohafia South II","Ohafia South III","Ohafia South IV","Ohafia East","Ohafia West"] },
      { name: "Osisioma Ngwa",    wards: w(10) },
      { name: "Ugwunagbo",        wards: w(10) },
      { name: "Ukwa East",        wards: w(10) },
      { name: "Ukwa West",        wards: w(10) },
      { name: "Umuahia North",    wards: ["Apumiri","Bende Road","Ibeku I","Ibeku II","Ibeku III","Nkwoegwu","Olokoro I","Olokoro II","Ubakala I","Ubakala II","Umuahia Urban"] },
      { name: "Umuahia South",    wards: w(10) },
      { name: "Umu Nneochi",      wards: w(10) },
    ],
  },
  {
    state: "Anambra", zone: "South East",
    lgas: [
      { name: "Aguata",           wards: ["Aguata I","Aguata II","Aguata III","Aguata IV","Aguata V","Aguata VI","Aguata VII","Aguata VIII","Aguata IX","Aguata X"] },
      { name: "Anambra East",     wards: w(11) },
      { name: "Anambra West",     wards: w(11) },
      { name: "Anaocha",          wards: w(10) },
      { name: "Awka North",       wards: w(10) },
      { name: "Awka South",       wards: ["Amawbia I","Amawbia II","Awka I","Awka II","Awka III","Awka IV","Awka V","Nibo","Okpuno","Oka"] },
      { name: "Ayamelum",         wards: w(11) },
      { name: "Dunukofia",        wards: w(10) },
      { name: "Ekwusigo",         wards: w(10) },
      { name: "Idemili North",    wards: w(13) },
      { name: "Idemili South",    wards: w(10) },
      { name: "Ihiala",           wards: w(13) },
      { name: "Njikoka",          wards: w(10) },
      { name: "Nnewi North",      wards: ["Nnewi I","Nnewi II","Nnewi III","Nnewi IV","Nnewi V","Nnewi VI","Nnewi VII","Nnewi VIII","Nnewi IX","Nnewi X"] },
      { name: "Nnewi South",      wards: w(10) },
      { name: "Ogbaru",           wards: w(13) },
      { name: "Onitsha North",    wards: ["Inland Town I","Inland Town II","Inland Town III","Fegge I","Fegge II","GRA","Odoakpu I","Odoakpu II","Trans Nkisi I","Trans Nkisi II"] },
      { name: "Onitsha South",    wards: w(10) },
      { name: "Orumba North",     wards: w(11) },
      { name: "Orumba South",     wards: w(10) },
      { name: "Oyi",              wards: w(10) },
    ],
  },
  {
    state: "Ebonyi", zone: "South East",
    lgas: [
      { name: "Abakaliki",        wards: ["Abakaliki I","Abakaliki II","Abakaliki III","Abakaliki IV","Abakaliki V","Abakaliki VI","Abakaliki VII","Abakaliki VIII","Abakaliki IX","Abakaliki X","Abakaliki XI","Abakaliki XII","Abakaliki XIII"] },
      { name: "Afikpo North",     wards: w(13) },
      { name: "Afikpo South",     wards: w(13) },
      { name: "Ebonyi",           wards: w(13) },
      { name: "Ezza North",       wards: w(13) },
      { name: "Ezza South",       wards: w(13) },
      { name: "Ikwo",             wards: w(13) },
      { name: "Ishielu",          wards: w(13) },
      { name: "Ivo",              wards: w(11) },
      { name: "Izzi",             wards: w(13) },
      { name: "Ohaozara",         wards: w(13) },
      { name: "Ohaukwu",          wards: w(13) },
      { name: "Onicha",           wards: w(11) },
    ],
  },
  {
    state: "Enugu", zone: "South East",
    lgas: [
      { name: "Aninri",           wards: w(11) },
      { name: "Awgu",             wards: w(13) },
      { name: "Enugu East",       wards: ["Abakpa I","Abakpa II","Achara Layout","Independence Layout","Mtanda","New Haven I","New Haven II","Obiagu I","Obiagu II","Ogui I","Ogui II","Ogui III","Trans Ekulu"] },
      { name: "Enugu North",      wards: ["Asata I","Asata II","Coal Camp I","Coal Camp II","Enugu North I","Enugu North II","GRA I","GRA II","Ogui Urban I","Ogui Urban II"] },
      { name: "Enugu South",      wards: ["Awkunanaw I","Awkunanaw II","Awkunanaw III","Garki I","Garki II","Garriki I","Garriki II","Ugwuaji I","Ugwuaji II","Uwani I","Uwani II"] },
      { name: "Ezeagu",           wards: w(13) },
      { name: "Igbo Etiti",       wards: w(13) },
      { name: "Igbo Eze North",   wards: w(13) },
      { name: "Igbo Eze South",   wards: w(13) },
      { name: "Isi Uzo",          wards: w(11) },
      { name: "Nkanu East",       wards: w(11) },
      { name: "Nkanu West",       wards: w(13) },
      { name: "Nsukka",           wards: ["Ehalumona","Enugo-Ezike I","Enugo-Ezike II","Nsukka I","Nsukka II","Nsukka III","Nsukka IV","Obimo","Okpuje","Opi","Orba I","Orba II","Ovoko"] },
      { name: "Oji River",        wards: w(11) },
      { name: "Udenu",            wards: w(11) },
      { name: "Udi",              wards: ["Agbudu","Ebe","Egede","Eke","Ngwo I","Ngwo II","Obioma","Oghu","Udi I","Udi II","Umuaga"] },
      { name: "Uzo Uwani",        wards: w(11) },
    ],
  },
  {
    state: "Imo", zone: "South East",
    lgas: [
      { name: "Aboh Mbaise",      wards: w(11) },
      { name: "Ahiazu Mbaise",    wards: w(11) },
      { name: "Ehime Mbano",      wards: w(11) },
      { name: "Ezinihitte",       wards: w(11) },
      { name: "Ideato North",     wards: w(11) },
      { name: "Ideato South",     wards: w(11) },
      { name: "Ihitte/Uboma",     wards: w(11) },
      { name: "Ikeduru",          wards: w(11) },
      { name: "Isiala Mbano",     wards: w(11) },
      { name: "Isu",              wards: w(11) },
      { name: "Mbaitoli",         wards: w(11) },
      { name: "Ngor Okpala",      wards: w(11) },
      { name: "Njaba",            wards: w(11) },
      { name: "Nkwerre",          wards: w(11) },
      { name: "Nwangele",         wards: w(11) },
      { name: "Obowo",            wards: w(11) },
      { name: "Oguta",            wards: w(11) },
      { name: "Ohaji/Egbema",     wards: w(11) },
      { name: "Okigwe",           wards: w(11) },
      { name: "Onuimo",           wards: w(11) },
      { name: "Orlu",             wards: ["Orlu I","Orlu II","Orlu III","Orlu IV","Orlu V","Orlu VI","Orlu VII","Orlu VIII","Orlu IX","Orlu X","Orlu XI"] },
      { name: "Orsu",             wards: w(11) },
      { name: "Oru East",         wards: w(11) },
      { name: "Oru West",         wards: w(11) },
      { name: "Owerri Municipal", wards: ["Aladinma I","Aladinma II","GRA I","GRA II","Ikenegbu I","Ikenegbu II","Imo","MCC Road","Old Owerri I","Old Owerri II","Wetheral"] },
      { name: "Owerri North",     wards: w(11) },
      { name: "Owerri West",      wards: w(11) },
    ],
  },

  // ── SOUTH SOUTH ──────────────────────────────────────────────────────────
  {
    state: "Akwa Ibom", zone: "South South",
    lgas: [
      { name: "Abak",             wards: w(10) },
      { name: "Eastern Obolo",    wards: w(10) },
      { name: "Eket",             wards: ["Eket I","Eket II","Eket III","Eket IV","Eket V","Eket VI","Eket VII","Eket VIII","Eket IX","Eket X"] },
      { name: "Esit Eket",        wards: w(10) },
      { name: "Essien Udim",      wards: w(11) },
      { name: "Etim Ekpo",        wards: w(10) },
      { name: "Etinan",           wards: w(10) },
      { name: "Ibeno",            wards: w(10) },
      { name: "Ibesikpo Asutan",  wards: w(10) },
      { name: "Ibiono Ibom",      wards: w(11) },
      { name: "Ika",              wards: w(10) },
      { name: "Ikono",            wards: w(10) },
      { name: "Ikot Abasi",       wards: w(11) },
      { name: "Ikot Ekpene",      wards: ["Ikot Ekpene I","Ikot Ekpene II","Ikot Ekpene III","Ikot Ekpene IV","Ikot Ekpene V","Ikot Ekpene VI","Ikot Ekpene VII","Ikot Ekpene VIII","Ikot Ekpene IX","Ikot Ekpene X"] },
      { name: "Ini",              wards: w(11) },
      { name: "Itu",              wards: w(11) },
      { name: "Mbo",              wards: w(10) },
      { name: "Mkpat Enin",       wards: w(11) },
      { name: "Nsit Atai",        wards: w(10) },
      { name: "Nsit Ibom",        wards: w(10) },
      { name: "Nsit Ubium",       wards: w(10) },
      { name: "Obot Akara",       wards: w(10) },
      { name: "Okobo",            wards: w(10) },
      { name: "Onna",             wards: w(10) },
      { name: "Oron",             wards: w(10) },
      { name: "Oruk Anam",        wards: w(11) },
      { name: "Udung Uko",        wards: w(10) },
      { name: "Ukanafun",         wards: w(10) },
      { name: "Uruan",            wards: w(10) },
      { name: "Urue Offong/Oruko",wards: w(10) },
      { name: "Uyo",              wards: ["Uyo I","Uyo II","Uyo III","Uyo IV","Uyo V","Uyo VI","Uyo VII","Uyo VIII","Uyo IX","Uyo X","Uyo XI"] },
    ],
  },
  {
    state: "Bayelsa", zone: "South South",
    lgas: [
      { name: "Brass",            wards: ["Akassa","Brass I","Brass II","Ewoama","Liama","Nembe Creek","Okpoama","Olodiama I","Olodiama II","Twon-Brass"] },
      { name: "Ekeremor",         wards: w(13) },
      { name: "Kolokuma/Opokuma", wards: w(13) },
      { name: "Nembe",            wards: ["Bassambiri I","Bassambiri II","Ogbolomabiri I","Ogbolomabiri II","Nembe I","Nembe II","Nembe III","Nembe IV","Nembe V","Nembe VI","Nembe VII","Nembe VIII","Nembe IX"] },
      { name: "Ogbia",            wards: ["Oloibiri","Ogbia I","Ogbia II","Ogbia III","Ogbia IV","Ogbia V","Ogbia VI","Ogbia VII","Ogbia VIII","Ogbia IX","Ogbia X","Ogbia XI","Kolo"] },
      { name: "Sagbama",          wards: w(13) },
      { name: "Southern Ijaw",    wards: w(13) },
      { name: "Yenagoa",          wards: ["Agudama-Epie","Biogbolo-Epie","Ekeki","Imgbi","Kpansia","Okutukutu","Opolo","Onopa","Toru-Orua","Yenagoa I","Yenagoa II","Yenagoa III","Yenagoa IV"] },
    ],
  },
  {
    state: "Cross River", zone: "South South",
    lgas: [
      { name: "Abi",              wards: w(10) },
      { name: "Akamkpa",          wards: w(11) },
      { name: "Akpabuyo",         wards: w(10) },
      { name: "Bakassi",          wards: w(10) },
      { name: "Bekwarra",         wards: w(10) },
      { name: "Biase",            wards: w(11) },
      { name: "Boki",             wards: w(11) },
      { name: "Calabar Municipal",wards: ["Atimbo","Calabar South I","Calabar South II","Esuk Oron","Mbukpa","Satellite Town","State Housing I","State Housing II","Wapi","Ikot Ishie"] },
      { name: "Calabar South",    wards: w(10) },
      { name: "Etung",            wards: w(10) },
      { name: "Ikom",             wards: w(11) },
      { name: "Obanliku",         wards: w(10) },
      { name: "Obubra",           wards: w(11) },
      { name: "Obudu",            wards: w(11) },
      { name: "Odukpani",         wards: w(10) },
      { name: "Ogoja",            wards: w(11) },
      { name: "Yakuur",           wards: w(10) },
      { name: "Yala",             wards: w(11) },
    ],
  },
  {
    state: "Delta", zone: "South South",
    lgas: [
      { name: "Aniocha North",    wards: w(10) },
      { name: "Aniocha South",    wards: w(10) },
      { name: "Bomadi",           wards: w(10) },
      { name: "Burutu",           wards: w(11) },
      { name: "Ethiope East",     wards: w(11) },
      { name: "Ethiope West",     wards: w(11) },
      { name: "Ika North East",   wards: w(11) },
      { name: "Ika South",        wards: w(10) },
      { name: "Isoko North",      wards: w(10) },
      { name: "Isoko South",      wards: w(11) },
      { name: "Ndokwa East",      wards: w(10) },
      { name: "Ndokwa West",      wards: w(11) },
      { name: "Okpe",             wards: w(10) },
      { name: "Oshimili North",   wards: w(10) },
      { name: "Oshimili South",   wards: w(11) },
      { name: "Patani",           wards: w(10) },
      { name: "Sapele",           wards: ["Amukpe I","Amukpe II","Okirigwre","Okpe I","Okpe II","Sapele I","Sapele II","Sapele III","Sapele IV","Sapele V"] },
      { name: "Udu",              wards: w(10) },
      { name: "Ughelli North",    wards: ["Agbarho I","Agbarho II","Evwreni","Ogor","Ughelli I","Ughelli II","Ughelli III","Ughelli IV","Ughelli V","Ughelli VI","Ughelli VII"] },
      { name: "Ughelli South",    wards: w(10) },
      { name: "Ukwuani",          wards: w(10) },
      { name: "Uvwie",            wards: w(10) },
      { name: "Warri North",      wards: w(10) },
      { name: "Warri South",      wards: ["Bowen","Deco Road","Edjeba I","Edjeba II","Ekurede Itsekiri","Ekurede Urhobo","Igbudu","Okere I","Okere II","Pessu","Okumagba I","Okumagba II"] },
      { name: "Warri South West", wards: w(10) },
    ],
  },
  {
    state: "Edo", zone: "South South",
    lgas: [
      { name: "Akoko-Edo",        wards: w(10) },
      { name: "Egor",             wards: ["Egba","Evbuotubu","Ikpoba Hill I","Ikpoba Hill II","Ogiso","Oregbeni I","Oregbeni II","Iguosa","Okhoro","Urubi"] },
      { name: "Esan Central",     wards: w(10) },
      { name: "Esan North East",  wards: w(10) },
      { name: "Esan South East",  wards: w(10) },
      { name: "Esan West",        wards: w(10) },
      { name: "Etsako Central",   wards: w(10) },
      { name: "Etsako East",      wards: w(10) },
      { name: "Etsako West",      wards: w(11) },
      { name: "Igueben",          wards: w(10) },
      { name: "Ikpoba-Okha",      wards: w(11) },
      { name: "Orhionmwon",       wards: w(10) },
      { name: "Oredo",            wards: ["Adesuwa Grammar","Airport Road","Benin I","Benin II","Benin III","GRA I","GRA II","Ikpoba Slope","King Square","New Benin I","New Benin II","New Benin III"] },
      { name: "Ovia North East",  wards: w(11) },
      { name: "Ovia South West",  wards: w(10) },
      { name: "Owan East",        wards: w(10) },
      { name: "Owan West",        wards: w(10) },
      { name: "Uhunmwonde",       wards: w(10) },
    ],
  },
  {
    state: "Rivers", zone: "South South",
    lgas: [
      { name: "Abua/Odual",       wards: w(13) },
      { name: "Ahoada East",      wards: w(11) },
      { name: "Ahoada West",      wards: w(11) },
      { name: "Akuku-Toru",       wards: w(13) },
      { name: "Andoni",           wards: w(13) },
      { name: "Asari-Toru",       wards: w(11) },
      { name: "Bonny",            wards: ["Bonny I","Bonny II","Bonny III","Bonny IV","Bonny V","Bonny VI","Bonny VII","Bonny VIII","Finima","Peterside"] },
      { name: "Degema",           wards: w(13) },
      { name: "Eleme",            wards: ["Agbonchia","Aleto","Ebubu","Ekporo","Eleme I","Eleme II","Ogale","Okpoka","Onne","Rumuolumeni"] },
      { name: "Emohua",           wards: w(11) },
      { name: "Etche",            wards: w(13) },
      { name: "Gokana",           wards: w(10) },
      { name: "Ikwerre",          wards: w(11) },
      { name: "Khana",            wards: w(13) },
      { name: "Obio/Akpor",       wards: ["Choba","Elimgbu","Mgbuoba I","Mgbuoba II","Obio I","Obio II","Obio III","Rumuigbo","Rumuola","Rumuosi I","Rumuosi II","Trans Amadi I","Trans Amadi II"] },
      { name: "Ogba/Egbema/Ndoni",wards: w(13) },
      { name: "Ogu/Bolo",         wards: w(10) },
      { name: "Okrika",           wards: w(11) },
      { name: "Omuma",            wards: w(10) },
      { name: "Opobo/Nkoro",      wards: w(10) },
      { name: "Oyigbo",           wards: w(10) },
      { name: "Port Harcourt City",wards: ["Diobu I","Diobu II","Diobu III","Diobu IV","Elegbam","GRA I","GRA II","Mile I","Mile II","Old GRA","Rumuola","Town I","Town II"] },
      { name: "Tai",              wards: w(10) },
    ],
  },

  // ── SOUTH WEST ────────────────────────────────────────────────────────────
  {
    state: "Ekiti", zone: "South West",
    lgas: [
      { name: "Ado Ekiti",        wards: ["Ado I","Ado II","Ado III","Ado IV","Ado V","Ado VI","Ado VII","Ado VIII","Ado IX","Ado X","Ado XI"] },
      { name: "Efon",             wards: w(10) },
      { name: "Ekiti East",       wards: w(11) },
      { name: "Ekiti South West", wards: w(11) },
      { name: "Ekiti West",       wards: w(11) },
      { name: "Emure",            wards: w(10) },
      { name: "Gbonyin",          wards: w(11) },
      { name: "Ido Osi",          wards: w(11) },
      { name: "Ijero",            wards: w(11) },
      { name: "Ikere",            wards: w(11) },
      { name: "Ikole",            wards: w(11) },
      { name: "Ilejemeje",        wards: w(10) },
      { name: "Irepodun/Ifelodun",wards: w(11) },
      { name: "Ise/Orun",         wards: w(11) },
      { name: "Moba",             wards: w(11) },
      { name: "Oye",              wards: w(11) },
    ],
  },
  {
    state: "Lagos", zone: "South West",
    lgas: [
      { name: "Agege",            wards: ["Agege I","Agege II","Agege III","Agege IV","Agege V","Agege VI","Agege VII","Agege VIII","Agege IX","Agege X","Agege XI","Agege XII"] },
      { name: "Ajeromi-Ifelodun", wards: w(12) },
      { name: "Alimosho",         wards: ["Egbeda I","Egbeda II","Egbeda III","Ikotun I","Ikotun II","Ikotun III","Idimu I","Idimu II","Igando I","Igando II","Ipaja I","Ipaja II","Shasha I","Shasha II"] },
      { name: "Amuwo-Odofin",     wards: w(10) },
      { name: "Apapa",            wards: ["Apapa I","Apapa II","Apapa III","Apapa IV","Apapa V","Apapa VI","Apapa VII","Apapa VIII","Apapa IX","Apapa X"] },
      { name: "Badagry",          wards: w(11) },
      { name: "Epe",              wards: w(11) },
      { name: "Eti-Osa",          wards: ["Ikate/Elegushi","Lekki I","Lekki II","Maroko","Obalende","Oniru","Victoria Island I","Victoria Island II","Victoria Island III","Ikoyi I","Ikoyi II","Ikoyi III"] },
      { name: "Ibeju-Lekki",      wards: w(10) },
      { name: "Ifako-Ijaiye",     wards: w(11) },
      { name: "Ikeja",            wards: ["Allen Avenue","Alausa","Ikeja I","Ikeja II","Ikeja III","Ikeja IV","Ojodu I","Ojodu II","Onigbongbo I","Onigbongbo II","Oregun I","Oregun II"] },
      { name: "Ikorodu",          wards: ["Gberigbe","Igbogbo I","Igbogbo II","Ikorodu Central I","Ikorodu Central II","Ikorodu Central III","Imota","Ipakodo","Isiu","Itamaga","Ijede","Odogunyan","Owutu"] },
      { name: "Kosofe",           wards: w(11) },
      { name: "Lagos Island",     wards: ["Catholic Mission","Epetedo","Idumota I","Idumota II","Lafiaji","Lagos Island I","Lagos Island II","Lagos Island III","Olowogbowo","Sandgrouse","Tokunbo","Tafawa Balewa"] },
      { name: "Lagos Mainland",   wards: w(12) },
      { name: "Mushin",           wards: w(12) },
      { name: "Ojo",              wards: w(11) },
      { name: "Oshodi-Isolo",     wards: w(12) },
      { name: "Shomolu",          wards: w(10) },
      { name: "Surulere",         wards: ["Aguda I","Aguda II","Bode Thomas","Coker/Aguda","Ijeshatedo I","Ijeshatedo II","Itire-Ikate I","Itire-Ikate II","Ojuelegba","Shitta","Surulere I","Surulere II"] },
    ],
  },
  {
    state: "Ogun", zone: "South West",
    lgas: [
      { name: "Abeokuta North",   wards: w(11) },
      { name: "Abeokuta South",   wards: w(11) },
      { name: "Ado-Odo/Ota",      wards: w(11) },
      { name: "Egbado North",     wards: w(11) },
      { name: "Egbado South",     wards: w(11) },
      { name: "Ewekoro",          wards: w(10) },
      { name: "Ifo",              wards: w(11) },
      { name: "Ijebu East",       wards: w(11) },
      { name: "Ijebu North",      wards: w(11) },
      { name: "Ijebu North East", wards: w(10) },
      { name: "Ijebu Ode",        wards: w(11) },
      { name: "Ikenne",           wards: w(10) },
      { name: "Imeko Afon",       wards: w(10) },
      { name: "Ipokia",           wards: w(10) },
      { name: "Obafemi Owode",    wards: w(11) },
      { name: "Odeda",            wards: w(10) },
      { name: "Odogbolu",         wards: w(10) },
      { name: "Ogun Waterside",   wards: w(10) },
      { name: "Remo North",       wards: w(10) },
      { name: "Sagamu",           wards: w(11) },
    ],
  },
  {
    state: "Ondo", zone: "South West",
    lgas: [
      { name: "Akoko North East", wards: w(11) },
      { name: "Akoko North West", wards: w(11) },
      { name: "Akoko South East", wards: w(11) },
      { name: "Akoko South West", wards: w(11) },
      { name: "Akure North",      wards: w(10) },
      { name: "Akure South",      wards: ["Alagbaka","Araromi-Obu","GRA I","GRA II","Ijoka","Isikan","Oda Road","Oshinle","Oke-Aro","Shagari Village","Ijoba"] },
      { name: "Ese Odo",          wards: w(10) },
      { name: "Idanre",           wards: w(10) },
      { name: "Ifedore",          wards: w(10) },
      { name: "Ilaje",            wards: w(11) },
      { name: "Ile Oluji/Okeigbo",wards: w(10) },
      { name: "Irele",            wards: w(10) },
      { name: "Odigbo",           wards: w(11) },
      { name: "Okitipupa",        wards: w(11) },
      { name: "Ondo East",        wards: w(10) },
      { name: "Ondo West",        wards: w(11) },
      { name: "Ose",              wards: w(11) },
      { name: "Owo",              wards: w(11) },
    ],
  },
  {
    state: "Osun", zone: "South West",
    lgas: [
      { name: "Aiyedaade",        wards: w(11) },
      { name: "Aiyedire",         wards: w(10) },
      { name: "Atakumosa East",   wards: w(10) },
      { name: "Atakumosa West",   wards: w(10) },
      { name: "Boluwaduro",       wards: w(10) },
      { name: "Boripe",           wards: w(11) },
      { name: "Ede North",        wards: w(10) },
      { name: "Ede South",        wards: w(10) },
      { name: "Egbedore",         wards: w(10) },
      { name: "Ejigbo",           wards: w(11) },
      { name: "Ife Central",      wards: w(11) },
      { name: "Ife East",         wards: w(11) },
      { name: "Ife North",        wards: w(10) },
      { name: "Ife South",        wards: w(10) },
      { name: "Ifedayo",          wards: w(10) },
      { name: "Ifelodun",         wards: w(11) },
      { name: "Ila",              wards: w(11) },
      { name: "Ilesa East",       wards: w(11) },
      { name: "Ilesa West",       wards: w(11) },
      { name: "Irepodun",         wards: w(11) },
      { name: "Irewole",          wards: w(11) },
      { name: "Isokan",           wards: w(10) },
      { name: "Iwo",              wards: w(11) },
      { name: "Obokun",           wards: w(11) },
      { name: "Odo Otin",         wards: w(11) },
      { name: "Ola Oluwa",        wards: w(10) },
      { name: "Olorunda",         wards: w(11) },
      { name: "Oriade",           wards: w(11) },
      { name: "Orolu",            wards: w(10) },
      { name: "Osogbo",           wards: ["Ayetoro","Ilesa Road","Igbona I","Igbona II","Oke-Baale I","Oke-Baale II","Okinni","Osogbo I","Osogbo II","Osogbo III","Osogbo IV"] },
    ],
  },
  {
    state: "Oyo", zone: "South West",
    lgas: [
      { name: "Afijio",           wards: w(10) },
      { name: "Akinyele",         wards: w(12) },
      { name: "Atiba",            wards: w(10) },
      { name: "Atisbo",           wards: w(10) },
      { name: "Egbeda",           wards: w(10) },
      { name: "Ibadan North",     wards: ["Agodi","Bashorun I","Bashorun II","Bodija I","Bodija II","Felele","Gbagi","Idi-Ape","Sango","UI"] },
      { name: "Ibadan North East",wards: w(10) },
      { name: "Ibadan North West",wards: w(10) },
      { name: "Ibadan South East",wards: w(10) },
      { name: "Ibadan South West",wards: ["Adeoyo","Agbowo","Alalubosa I","Alalubosa II","Ekotedo","Iyaganku I","Iyaganku II","Oke Ado","Ring Road","Yemetu I","Yemetu II"] },
      { name: "Ibarapa Central",  wards: w(10) },
      { name: "Ibarapa East",     wards: w(10) },
      { name: "Ibarapa North",    wards: w(10) },
      { name: "Ido",              wards: w(10) },
      { name: "Ifedapo",          wards: w(10) },
      { name: "Irepo",            wards: w(10) },
      { name: "Iseyin",           wards: w(11) },
      { name: "Itesiwaju",        wards: w(10) },
      { name: "Iwajowa",          wards: w(10) },
      { name: "Kajola",           wards: w(10) },
      { name: "Lagelu",           wards: w(10) },
      { name: "Ogbomosho North",  wards: w(11) },
      { name: "Ogbomosho South",  wards: w(10) },
      { name: "Ogo Oluwa",        wards: w(10) },
      { name: "Olorunsogo",       wards: w(10) },
      { name: "Oluyole",          wards: w(10) },
      { name: "Ona Ara",          wards: w(10) },
      { name: "Orelope",          wards: w(10) },
      { name: "Ori Ire",          wards: w(10) },
      { name: "Oyo East",         wards: w(10) },
      { name: "Oyo West",         wards: w(10) },
      { name: "Saki East",        wards: w(10) },
      { name: "Saki West",        wards: w(11) },
    ],
  },

  // ── NORTH CENTRAL ─────────────────────────────────────────────────────────
  {
    state: "Benue", zone: "North Central",
    lgas: [
      { name: "Ado",              wards: w(11) },
      { name: "Agatu",            wards: w(10) },
      { name: "Apa",              wards: w(10) },
      { name: "Buruku",           wards: w(11) },
      { name: "Gboko",            wards: ["Gboko East I","Gboko East II","Gboko North I","Gboko North II","Gboko South I","Gboko South II","Gboko West I","Gboko West II","Mbagba","Mbaapen","Mbalom"] },
      { name: "Guma",             wards: w(11) },
      { name: "Gwer East",        wards: w(11) },
      { name: "Gwer West",        wards: w(11) },
      { name: "Katsina-Ala",      wards: w(13) },
      { name: "Konshisha",        wards: w(11) },
      { name: "Kwande",           wards: w(13) },
      { name: "Logo",             wards: w(11) },
      { name: "Makurdi",          wards: ["Agan","Ankpa Ward","GRA","High Level I","High Level II","Judges Quarters","Kanshio","Mbalagh","Northbank I","Northbank II","Old GRA","Wadata I","Wadata II"] },
      { name: "Obi",              wards: w(10) },
      { name: "Ogbadibo",         wards: w(11) },
      { name: "Ohimini",          wards: w(10) },
      { name: "Oju",              wards: w(11) },
      { name: "Okpokwu",          wards: w(11) },
      { name: "Otukpo",           wards: w(13) },
      { name: "Tarka",            wards: w(10) },
      { name: "Ukum",             wards: w(11) },
      { name: "Ushongo",          wards: w(11) },
      { name: "Vandeikya",        wards: w(13) },
    ],
  },
  {
    state: "FCT", zone: "North Central",
    lgas: [
      { name: "Abaji",            wards: w(10) },
      { name: "Bwari",            wards: ["Bwari","Dutse-Alhaji","Byazhin","Garam","Igu","Kawu","Kubwa I","Kubwa II","Ushafa","Usuma"] },
      { name: "Gwagwalada",       wards: ["Dobi","Gwagwalada Central","Gwagwalada North","Gwagwalada South","Gwako","Ibwa","Ikwa","Paikon-Kore","Zungu","Zuba"] },
      { name: "Kuje",             wards: w(11) },
      { name: "Kwali",            wards: w(10) },
      { name: "Municipal Area Council", wards: ["Asokoro","Cadastral Zone","Central Business District","Durumi","Garki I","Garki II","Guzape","Jabi","Maitama","Wuse I","Wuse II","Wuye"] },
    ],
  },
  {
    state: "Kogi", zone: "North Central",
    lgas: [
      { name: "Adavi",            wards: w(10) },
      { name: "Ajaokuta",         wards: w(10) },
      { name: "Ankpa",            wards: w(11) },
      { name: "Bassa",            wards: w(11) },
      { name: "Dekina",           wards: w(11) },
      { name: "Ibaji",            wards: w(10) },
      { name: "Idah",             wards: w(11) },
      { name: "Igalamela-Odolu",  wards: w(11) },
      { name: "Ijumu",            wards: w(10) },
      { name: "Kabba/Bunu",       wards: w(11) },
      { name: "Kogi",             wards: w(10) },
      { name: "Lokoja",           wards: ["Adankolo","Ajaokuta Road","Felele","Ganaja","Gadumo","Lokoja I","Lokoja II","Lokoja III","Lokoja IV","Natala","Zango"] },
      { name: "Mopa-Muro",        wards: w(10) },
      { name: "Ofu",              wards: w(11) },
      { name: "Ogori/Magongo",    wards: w(10) },
      { name: "Okehi",            wards: w(10) },
      { name: "Okene",            wards: ["Eba","Ihima","Obagaji","Okehi I","Okene I","Okene II","Okene III","Okene IV","Okene V","Upogoro","Uzere"] },
      { name: "Olamaboro",        wards: w(11) },
      { name: "Omala",            wards: w(10) },
      { name: "Yagba East",       wards: w(10) },
      { name: "Yagba West",       wards: w(10) },
    ],
  },
  {
    state: "Kwara", zone: "North Central",
    lgas: [
      { name: "Asa",              wards: w(11) },
      { name: "Baruten",          wards: w(11) },
      { name: "Edu",              wards: w(11) },
      { name: "Ekiti",            wards: w(10) },
      { name: "Ifelodun",         wards: w(11) },
      { name: "Ilorin East",      wards: w(11) },
      { name: "Ilorin South",     wards: w(11) },
      { name: "Ilorin West",      wards: ["Ajanaku","Ajikobi","Baboko","Balogun Fulani","Dada","Gaa Akanbi","Gaa Imam","Magaji Are","Okekere","Pakata","Sango","Unity"] },
      { name: "Irepodun",         wards: w(11) },
      { name: "Isin",             wards: w(10) },
      { name: "Kaiama",           wards: w(11) },
      { name: "Moro",             wards: w(11) },
      { name: "Offa",             wards: w(11) },
      { name: "Oke Ero",          wards: w(10) },
      { name: "Oyun",             wards: w(11) },
      { name: "Pategi",           wards: w(11) },
    ],
  },
  {
    state: "Nasarawa", zone: "North Central",
    lgas: [
      { name: "Akwanga",          wards: w(11) },
      { name: "Awe",              wards: w(11) },
      { name: "Doma",             wards: w(11) },
      { name: "Karu",             wards: ["Ado","Gitata","Karu I","Karu II","Kugbo","Kuje","Masaka","Mararaba I","Mararaba II","New Nyanya","Nyanya I","Nyanya II"] },
      { name: "Keana",            wards: w(10) },
      { name: "Keffi",            wards: ["Angwan Lambu","Angwan Maje","Bukan Sidi","Iya","Keffi I","Keffi II","Kofar Gaya","Mararaba Gurku","Sabon Gari","Tudun Gwandara","Ungwan Sarki"] },
      { name: "Kokona",           wards: w(10) },
      { name: "Lafia",            wards: ["Arikya","Doma Road","Gonchi","Lafia I","Lafia II","Lafia III","Lafia IV","Mararaba Lafia","Odu","Shabu","Station"] },
      { name: "Nasarawa",         wards: w(11) },
      { name: "Nasarawa Egon",    wards: w(11) },
      { name: "Obi",              wards: w(10) },
      { name: "Toto",             wards: w(11) },
      { name: "Wamba",            wards: w(10) },
    ],
  },
  {
    state: "Niger", zone: "North Central",
    lgas: [
      { name: "Agaie",            wards: w(10) },
      { name: "Agwara",           wards: w(10) },
      { name: "Bida",             wards: ["Bangi","Bida I","Bida II","Bida III","Bida IV","Ceniyan","Doko","Gwangi","Jima","Wuya"] },
      { name: "Borgu",            wards: w(11) },
      { name: "Bosso",            wards: w(10) },
      { name: "Chanchaga",        wards: ["Chanchaga I","Chanchaga II","Chanchaga III","Chanchaga IV","Chanchaga V","Chanchaga VI","Chanchaga VII","Chanchaga VIII","Minna I","Minna II"] },
      { name: "Edati",            wards: w(10) },
      { name: "Gbako",            wards: w(10) },
      { name: "Gurara",           wards: w(10) },
      { name: "Katcha",           wards: w(10) },
      { name: "Kontagora",        wards: w(11) },
      { name: "Lapai",            wards: w(10) },
      { name: "Lavun",            wards: w(10) },
      { name: "Magama",           wards: w(10) },
      { name: "Mariga",           wards: w(10) },
      { name: "Mashegu",          wards: w(10) },
      { name: "Mokwa",            wards: w(11) },
      { name: "Munya",            wards: w(10) },
      { name: "Paikoro",          wards: w(10) },
      { name: "Rafi",             wards: w(10) },
      { name: "Rijau",            wards: w(10) },
      { name: "Shiroro",          wards: w(11) },
      { name: "Suleja",           wards: ["Bagama I","Bagama II","Maje","Sabon Wuse I","Sabon Wuse II","Suleja I","Suleja II","Suleja III","Wamba","Tudun Fulani"] },
      { name: "Tafa",             wards: w(10) },
      { name: "Wushishi",         wards: w(10) },
    ],
  },
  {
    state: "Plateau", zone: "North Central",
    lgas: [
      { name: "Barkin Ladi",      wards: w(10) },
      { name: "Bassa",            wards: w(11) },
      { name: "Bokkos",           wards: w(11) },
      { name: "Jos East",         wards: w(10) },
      { name: "Jos North",        wards: ["Anguwan Rogo","Dogon Dutse","Gangare","GRA","Jos North I","Jos North II","Jos North III","Kabong","Kwararafa","Laranto","Tudun Wada North","Tudun Wada South"] },
      { name: "Jos South",        wards: w(12) },
      { name: "Kanam",            wards: w(11) },
      { name: "Kanke",            wards: w(11) },
      { name: "Langtang North",   wards: w(10) },
      { name: "Langtang South",   wards: w(10) },
      { name: "Mangu",            wards: w(11) },
      { name: "Mikang",           wards: w(10) },
      { name: "Pankshin",         wards: w(11) },
      { name: "Qua'an Pan",       wards: w(11) },
      { name: "Riyom",            wards: w(10) },
      { name: "Shendam",          wards: w(11) },
      { name: "Wase",             wards: w(11) },
    ],
  },

  // ── NORTH EAST ────────────────────────────────────────────────────────────
  {
    state: "Adamawa", zone: "North East",
    lgas: [
      { name: "Demsa",            wards: w(10) },
      { name: "Fufure",           wards: w(10) },
      { name: "Ganye",            wards: w(10) },
      { name: "Gayuk",            wards: w(10) },
      { name: "Gombi",            wards: w(10) },
      { name: "Grie",             wards: w(10) },
      { name: "Hong",             wards: w(10) },
      { name: "Jada",             wards: w(10) },
      { name: "Lamurde",          wards: w(10) },
      { name: "Madagali",         wards: w(10) },
      { name: "Maiha",            wards: w(10) },
      { name: "Mayo Belwa",       wards: w(11) },
      { name: "Michika",          wards: w(10) },
      { name: "Mubi North",       wards: w(11) },
      { name: "Mubi South",       wards: w(10) },
      { name: "Numan",            wards: w(10) },
      { name: "Shelleng",         wards: w(10) },
      { name: "Song",             wards: w(10) },
      { name: "Toungo",           wards: w(10) },
      { name: "Yola North",       wards: ["Doubeli","Girei","Jambutu I","Jambutu II","Limawa I","Limawa II","Nassarawo","Rumde","Yola I","Yola II","Yola III"] },
      { name: "Yola South",       wards: w(11) },
    ],
  },
  {
    state: "Bauchi", zone: "North East",
    lgas: [
      { name: "Alkaleri",         wards: w(10) },
      { name: "Bauchi",           wards: ["Bauchi Central I","Bauchi Central II","Bauchi East I","Bauchi East II","Bauchi North","Bauchi South","Bauchi West I","Bauchi West II","Dan Iya","Makama","Wunti"] },
      { name: "Bogoro",           wards: w(10) },
      { name: "Damban",           wards: w(10) },
      { name: "Darazo",           wards: w(10) },
      { name: "Dass",             wards: w(10) },
      { name: "Gamawa",           wards: w(10) },
      { name: "Ganjuwa",          wards: w(10) },
      { name: "Giade",            wards: w(10) },
      { name: "Itas/Gadau",       wards: w(10) },
      { name: "Jama'are",         wards: w(10) },
      { name: "Katagum",          wards: w(10) },
      { name: "Kirfi",            wards: w(10) },
      { name: "Misau",            wards: w(10) },
      { name: "Ningi",            wards: w(10) },
      { name: "Shira",            wards: w(10) },
      { name: "Tafawa Balewa",    wards: w(10) },
      { name: "Toro",             wards: w(10) },
      { name: "Warji",            wards: w(10) },
      { name: "Zaki",             wards: w(10) },
    ],
  },
  {
    state: "Borno", zone: "North East",
    lgas: [
      { name: "Abadam",           wards: w(10) },
      { name: "Askira/Uba",       wards: w(10) },
      { name: "Bama",             wards: w(11) },
      { name: "Bayo",             wards: w(10) },
      { name: "Biu",              wards: w(11) },
      { name: "Chibok",           wards: w(10) },
      { name: "Damboa",           wards: w(10) },
      { name: "Dikwa",            wards: w(10) },
      { name: "Gubio",            wards: w(10) },
      { name: "Guzamala",         wards: w(10) },
      { name: "Gwoza",            wards: w(10) },
      { name: "Hawul",            wards: w(10) },
      { name: "Jere",             wards: w(11) },
      { name: "Kaga",             wards: w(10) },
      { name: "Kala/Balge",       wards: w(10) },
      { name: "Konduga",          wards: w(10) },
      { name: "Kukawa",           wards: w(10) },
      { name: "Kwaya Kusar",      wards: w(10) },
      { name: "Mafa",             wards: w(10) },
      { name: "Magumeri",         wards: w(10) },
      { name: "Maiduguri",        wards: ["Bolori I","Bolori II","Bulabulin","Gamboru","GRA","Gwange I","Gwange II","Hausari","Lamisula","Mafoni","Shehuri North","Shehuri South"] },
      { name: "Marte",            wards: w(10) },
      { name: "Mobbar",           wards: w(10) },
      { name: "Monguno",          wards: w(10) },
      { name: "Ngala",            wards: w(10) },
      { name: "Nganzai",          wards: w(10) },
      { name: "Shani",            wards: w(10) },
    ],
  },
  {
    state: "Gombe", zone: "North East",
    lgas: [
      { name: "Akko",             wards: w(11) },
      { name: "Balanga",          wards: w(10) },
      { name: "Billiri",          wards: w(10) },
      { name: "Dukku",            wards: w(10) },
      { name: "Funakaye",         wards: w(10) },
      { name: "Gombe",            wards: ["Abubakar Kigo","Doma","Gabukka","Gombe Central I","Gombe Central II","Herwa I","Herwa II","Jekadafari I","Jekadafari II","Nasarawo","Tudun Wada"] },
      { name: "Kaltungo",         wards: w(10) },
      { name: "Kwami",            wards: w(10) },
      { name: "Nafada",           wards: w(10) },
      { name: "Shongom",          wards: w(10) },
      { name: "Yamaltu/Deba",     wards: w(11) },
    ],
  },
  {
    state: "Taraba", zone: "North East",
    lgas: [
      { name: "Ardo Kola",        wards: w(10) },
      { name: "Bali",             wards: w(10) },
      { name: "Donga",            wards: w(10) },
      { name: "Gashaka",          wards: w(10) },
      { name: "Gassol",           wards: w(11) },
      { name: "Ibi",              wards: w(10) },
      { name: "Jalingo",          wards: ["Ajiya","Barade","Dampar","Jalingo I","Jalingo II","Jalingo III","Kampani Lau","Kona","Mayo Gwoi","Yelwa"] },
      { name: "Karim Lamido",     wards: w(10) },
      { name: "Kumi",             wards: w(10) },
      { name: "Lau",              wards: w(10) },
      { name: "Sardauna",         wards: w(10) },
      { name: "Takum",            wards: w(11) },
      { name: "Ussa",             wards: w(10) },
      { name: "Wukari",           wards: w(11) },
      { name: "Yorro",            wards: w(10) },
      { name: "Zing",             wards: w(10) },
    ],
  },
  {
    state: "Yobe", zone: "North East",
    lgas: [
      { name: "Bade",             wards: w(10) },
      { name: "Bursari",          wards: w(10) },
      { name: "Damaturu",         wards: ["Bolori","Brodua","Damaturu East","Damaturu North","Damaturu South","Damaturu West","Gujba","Ngelzarma","Pawari","Warsala"] },
      { name: "Fika",             wards: w(10) },
      { name: "Fune",             wards: w(10) },
      { name: "Geidam",           wards: w(10) },
      { name: "Gujba",            wards: w(10) },
      { name: "Gulani",           wards: w(10) },
      { name: "Jakusko",          wards: w(10) },
      { name: "Karasuwa",         wards: w(10) },
      { name: "Machina",          wards: w(10) },
      { name: "Nangere",          wards: w(10) },
      { name: "Nguru",            wards: w(11) },
      { name: "Potiskum",         wards: ["Geidam Road","Ngurbuwa","Potiskum East","Potiskum North","Potiskum South","Potiskum West","Sasawa","Umara","Yunusari","Zadawa"] },
      { name: "Tarmua",           wards: w(10) },
      { name: "Yunusari",         wards: w(10) },
      { name: "Yusufari",         wards: w(10) },
    ],
  },

  // ── NORTH WEST ────────────────────────────────────────────────────────────
  {
    state: "Jigawa", zone: "North West",
    lgas: [
      { name: "Auyo",             wards: w(10) },
      { name: "Babura",           wards: w(10) },
      { name: "Biriniwa",         wards: w(10) },
      { name: "Birnin Kudu",      wards: w(11) },
      { name: "Buji",             wards: w(10) },
      { name: "Dutse",            wards: ["Dutse Central I","Dutse Central II","Dutse East","Dutse North","Dutse South","Dutse West","Fanisau","Kiyawa","Riruwai","Samamiji","Takur"] },
      { name: "Gagarawa",         wards: w(10) },
      { name: "Garki",            wards: w(10) },
      { name: "Gumel",            wards: w(10) },
      { name: "Guri",             wards: w(10) },
      { name: "Gwaram",           wards: w(10) },
      { name: "Gwiwa",            wards: w(10) },
      { name: "Hadejia",          wards: w(10) },
      { name: "Jahun",            wards: w(10) },
      { name: "Kafin Hausa",      wards: w(10) },
      { name: "Kaugama",          wards: w(10) },
      { name: "Kazaure",          wards: w(10) },
      { name: "Kiri Kasama",      wards: w(10) },
      { name: "Kiyawa",           wards: w(10) },
      { name: "Maigatari",        wards: w(10) },
      { name: "Malam Madori",     wards: w(10) },
      { name: "Miga",             wards: w(10) },
      { name: "Ringim",           wards: w(10) },
      { name: "Roni",             wards: w(10) },
      { name: "Sule Tankarkar",   wards: w(10) },
      { name: "Taura",            wards: w(10) },
      { name: "Yankwashi",        wards: w(10) },
    ],
  },
  {
    state: "Kaduna", zone: "North West",
    lgas: [
      { name: "Birnin Gwari",     wards: w(11) },
      { name: "Chikun",           wards: w(11) },
      { name: "Giwa",             wards: w(10) },
      { name: "Igabi",            wards: w(11) },
      { name: "Ikara",            wards: w(10) },
      { name: "Jaba",             wards: w(10) },
      { name: "Jema'a",           wards: w(11) },
      { name: "Kachia",           wards: w(11) },
      { name: "Kaduna North",     wards: ["Barnawa I","Barnawa II","Kabala Costain","Kaduna North I","Kaduna North II","Kakuri I","Kakuri II","Makera I","Makera II","Rafin Guza","Tudun Wada"] },
      { name: "Kaduna South",     wards: ["Badiko","Gonin Gora","Kabala West","Kaduna South I","Kaduna South II","Narayi","Nassarawa","Sabon Gari I","Sabon Gari II","Television","Unguwan Rimi"] },
      { name: "Kagarko",          wards: w(10) },
      { name: "Kajuru",           wards: w(10) },
      { name: "Kaura",            wards: w(10) },
      { name: "Kauru",            wards: w(10) },
      { name: "Kubau",            wards: w(10) },
      { name: "Kudan",            wards: w(10) },
      { name: "Lere",             wards: w(10) },
      { name: "Makarfi",          wards: w(10) },
      { name: "Sabon Gari",       wards: w(11) },
      { name: "Sanga",            wards: w(10) },
      { name: "Soba",             wards: w(10) },
      { name: "Zangon Kataf",     wards: w(11) },
      { name: "Zaria",            wards: ["Dambo","Gyallesu","Hanwa","Kwarbai A","Kwarbai B","Makarfi Road","Sabon Gari I","Sabon Gari II","Tukur-Tukur","Wuciciri","Zaria I","Zaria II"] },
    ],
  },
  {
    state: "Kano", zone: "North West",
    lgas: [
      { name: "Ajingi",           wards: w(10) },
      { name: "Albasu",           wards: w(10) },
      { name: "Bagwai",           wards: w(10) },
      { name: "Bebeji",           wards: w(10) },
      { name: "Bichi",            wards: w(10) },
      { name: "Bunkure",          wards: w(10) },
      { name: "Dala",             wards: ["Bachirawa","Dala I","Dala II","Dala III","Dala IV","Dala V","Kofar Dawanau","Kofar Kabuga","Kofar Kaura","Kofar Nassarawa","Kofar Wambai"] },
      { name: "Dambatta",         wards: w(10) },
      { name: "Dawakin Kudu",     wards: w(10) },
      { name: "Dawakin Tofa",     wards: w(10) },
      { name: "Doguwa",           wards: w(10) },
      { name: "Fagge",            wards: ["Fagge A","Fagge B","Fagge C","Fagge D","Fagge E","Fagge F","Fagge G","Kofar Mata","Kofar Ruwa","Zango"] },
      { name: "Gabasawa",         wards: w(10) },
      { name: "Garko",            wards: w(10) },
      { name: "Garun Mallam",     wards: w(10) },
      { name: "Gaya",             wards: w(11) },
      { name: "Gezawa",           wards: w(10) },
      { name: "Gwale",            wards: ["Gwale I","Gwale II","Gwale III","Gwale IV","Gwale V","Gwale VI","Gwale VII","Gwale VIII","Gwale IX","Gwale X"] },
      { name: "Gwarzo",           wards: w(10) },
      { name: "Kabo",             wards: w(10) },
      { name: "Kano Municipal",   wards: ["Diso","Kofar Danagundi","Kofar Naisa","Kofar Ruwa","Kofar Wambai","Kofar Waika","Kofar Yakasai","Kurna","Kwari","Sheshe","Tudun Wada"] },
      { name: "Karaye",           wards: w(10) },
      { name: "Kibiya",           wards: w(10) },
      { name: "Kiru",             wards: w(10) },
      { name: "Kumbotso",         wards: w(11) },
      { name: "Kunchi",           wards: w(10) },
      { name: "Kura",             wards: w(10) },
      { name: "Madobi",           wards: w(10) },
      { name: "Makoda",           wards: w(10) },
      { name: "Minjibir",         wards: w(10) },
      { name: "Nasarawa",         wards: ["Dangwauro","Farmhouse","Kantin Kwari","Nasarawa I","Nasarawa II","Nasarawa III","Naibawa","Rijiyar Lemu","Tudun Murtala","Yankaba"] },
      { name: "Rano",             wards: w(10) },
      { name: "Rimin Gado",       wards: w(10) },
      { name: "Rogo",             wards: w(10) },
      { name: "Shanono",          wards: w(10) },
      { name: "Sumaila",          wards: w(10) },
      { name: "Takai",            wards: w(10) },
      { name: "Tarauni",          wards: ["Danbare","Dorayi Karama","Dorayi Babba","Gyadi-Gyadi North","Gyadi-Gyadi South","Kawo I","Kawo II","Kawaji","Tarauni I","Tarauni II"] },
      { name: "Tofa",             wards: w(10) },
      { name: "Tsanyawa",         wards: w(10) },
      { name: "Tudun Wada",       wards: w(11) },
      { name: "Ungogo",           wards: w(10) },
      { name: "Warawa",           wards: w(10) },
      { name: "Wudil",            wards: w(10) },
    ],
  },
  {
    state: "Katsina", zone: "North West",
    lgas: [
      { name: "Bakori",           wards: w(10) },
      { name: "Batagarawa",       wards: w(10) },
      { name: "Batsari",          wards: w(10) },
      { name: "Baure",            wards: w(10) },
      { name: "Bindawa",          wards: w(10) },
      { name: "Charanchi",        wards: w(10) },
      { name: "Dan Musa",         wards: w(10) },
      { name: "Dandume",          wards: w(10) },
      { name: "Danja",            wards: w(10) },
      { name: "Daura",            wards: ["Daura Central I","Daura Central II","Daura East","Daura North","Daura South","Daura West","Doro","Katsalle","Zango","Zurfi"] },
      { name: "Dutsi",            wards: w(10) },
      { name: "Dutsin-Ma",        wards: w(10) },
      { name: "Faskari",          wards: w(10) },
      { name: "Funtua",           wards: w(10) },
      { name: "Ingawa",           wards: w(10) },
      { name: "Jibia",            wards: w(10) },
      { name: "Kafur",            wards: w(10) },
      { name: "Kaita",            wards: w(10) },
      { name: "Kankara",          wards: w(10) },
      { name: "Kankia",           wards: w(10) },
      { name: "Katsina",          wards: ["Katsina Central I","Katsina Central II","Katsina Central III","Katsina East","Katsina North","Katsina South","Katsina West","Kofar Marusa","Kofar Sauri","Kofar Yandaka","Unguwan Fatima"] },
      { name: "Kurfi",            wards: w(10) },
      { name: "Kusada",           wards: w(10) },
      { name: "Mai'adua",         wards: w(10) },
      { name: "Malumfashi",       wards: w(10) },
      { name: "Mani",             wards: w(10) },
      { name: "Mashi",            wards: w(10) },
      { name: "Matazu",           wards: w(10) },
      { name: "Musawa",           wards: w(10) },
      { name: "Rimi",             wards: w(10) },
      { name: "Sabuwa",           wards: w(10) },
      { name: "Safana",           wards: w(10) },
      { name: "Sandamu",          wards: w(10) },
      { name: "Zango",            wards: w(10) },
    ],
  },
  {
    state: "Kebbi", zone: "North West",
    lgas: [
      { name: "Aleiro",           wards: w(10) },
      { name: "Arewa Dandi",      wards: w(10) },
      { name: "Argungu",          wards: w(11) },
      { name: "Augie",            wards: w(10) },
      { name: "Bagudo",           wards: w(10) },
      { name: "Birnin Kebbi",     wards: ["Birnin Kebbi Central I","Birnin Kebbi Central II","Birnin Kebbi East","Birnin Kebbi North","Birnin Kebbi South","Birnin Kebbi West","Kalgo","Kambaza","Kardi","Makera","Matamu"] },
      { name: "Bunza",            wards: w(10) },
      { name: "Dandi",            wards: w(10) },
      { name: "Fakai",            wards: w(10) },
      { name: "Gwandu",           wards: w(10) },
      { name: "Jega",             wards: w(10) },
      { name: "Kalgo",            wards: w(10) },
      { name: "Koko/Besse",       wards: w(10) },
      { name: "Maiyama",          wards: w(10) },
      { name: "Ngaski",           wards: w(10) },
      { name: "Sakaba",           wards: w(10) },
      { name: "Shanga",           wards: w(10) },
      { name: "Suru",             wards: w(10) },
      { name: "Wasagu/Danko",     wards: w(10) },
      { name: "Yauri",            wards: w(11) },
      { name: "Zuru",             wards: w(11) },
    ],
  },
  {
    state: "Sokoto", zone: "North West",
    lgas: [
      { name: "Binji",            wards: w(10) },
      { name: "Bodinga",          wards: w(10) },
      { name: "Dange Shuni",      wards: w(10) },
      { name: "Gada",             wards: w(10) },
      { name: "Goronyo",          wards: w(10) },
      { name: "Gudu",             wards: w(10) },
      { name: "Gwadabawa",        wards: w(10) },
      { name: "Illela",           wards: w(10) },
      { name: "Isa",              wards: w(10) },
      { name: "Kebbe",            wards: w(10) },
      { name: "Kware",            wards: w(10) },
      { name: "Rabah",            wards: w(10) },
      { name: "Sabon Birni",      wards: w(10) },
      { name: "Shagari",          wards: w(10) },
      { name: "Silame",           wards: w(10) },
      { name: "Sokoto North",     wards: ["Arkilla","Gagi","Kware","Runjin Sambo","Sama","Sokoto North I","Sokoto North II","Sokoto North III","Sokoto North IV","Sokoto North V"] },
      { name: "Sokoto South",     wards: ["Gidan Dare","Gidan Igwai","Kofar Atiku","Kofar Rini","Kofar Sauri","Mabera I","Mabera II","Runjin Sarki","Sokoto South I","Sokoto South II"] },
      { name: "Tambuwal",         wards: w(11) },
      { name: "Tangaza",          wards: w(10) },
      { name: "Tureta",           wards: w(10) },
      { name: "Wamako",           wards: w(10) },
      { name: "Wurno",            wards: w(10) },
      { name: "Yabo",             wards: w(10) },
    ],
  },
  {
    state: "Zamfara", zone: "North West",
    lgas: [
      { name: "Anka",             wards: w(10) },
      { name: "Bakura",           wards: w(10) },
      { name: "Birnin Magaji/Kiyaw",wards: w(10) },
      { name: "Bukkuyum",         wards: w(10) },
      { name: "Bungudu",          wards: w(11) },
      { name: "Gummi",            wards: w(10) },
      { name: "Gusau",            wards: ["Gusau Central I","Gusau Central II","Gusau East","Gusau North","Gusau South","Gusau West","Kofar Fada","Mada","Sabon Gari","Tudun Wada","Yankama"] },
      { name: "Kaura Namoda",     wards: w(10) },
      { name: "Maradun",          wards: w(10) },
      { name: "Maru",             wards: w(10) },
      { name: "Shinkafi",         wards: w(10) },
      { name: "Talata Mafara",    wards: w(10) },
      { name: "Tsafe",            wards: w(10) },
      { name: "Zurmi",            wards: w(10) },
    ],
  },
];
